export const SAMPLE = [
  '# Markdown, the way you mean it',
  '',
  'A WYSIWYG editor that speaks **only** markdown — every button maps to something the spec supports, nothing more. Write on the left, read the source on the right.',
  '',
  '## Why it works',
  '',
  '- Format with the toolbar or familiar shortcuts (`⌘B`, `⌘I`)',
  '- Flip to **Source** for clean, portable markdown',
  '- Everything stays in sync, *both* directions',
  '',
  '### Task list',
  '',
  '- [x] Render markdown to a rich document',
  '- [x] Serialize edits back to markdown',
  '- [ ] Ship it',
  '',
  '> Markdown is a writing format. This editor keeps it that way — no hidden styles, no surprises.',
  '',
  '### A small table',
  '',
  '| Element | Shortcut | Markdown |',
  '| ------- | -------- | -------- |',
  '| Bold    | ⌘B       | `**x**`  |',
  '| Italic  | ⌘I       | `*x*`    |',
  '| Code    | —        | `` `x` `` |',
  '',
  'Inline `code` and fenced blocks both render:',
  '',
  '```js',
  'function greet(name) {',
  '  return `hello, ${name}`;',
  '}',
  '```',
  '',
  '[Read the CommonMark spec](https://commonmark.org) for the full grammar.',
  '',
  '---',
  '',
  "Drop an image, add a heading, make a list — it's all just text underneath.",
].join('\n')

export const DEFAULT_TABLE =
  '<table><thead><tr><th>Column A</th><th>Column B</th></tr></thead><tbody><tr><td>Cell</td><td>Cell</td></tr><tr><td>Cell</td><td>Cell</td></tr></tbody></table><p><br></p>'
